--- !ditz.rubyforge.org,2008-03-06/project 
name: django-bingo
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: django-bingo
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.0.0
  status: :released
  release_time: 2013-09-10 22:30:42 Z
  log_events: 
  - - 2013-09-12 23:05:01.756848 Z
    - Alexander Schier <allo@laxu.de>
    - created
    - ""
  - - 2013-09-12 23:05:33.478481 Z
    - Alexander Schier <allo@laxu.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.1.0
  status: :released
  release_time: 2013-09-14 09:52:07.033804 Z
  log_events: 
  - - 2013-09-12 23:07:08.362653 Z
    - Alexander Schier <allo@laxu.de>
    - created
    - ""
  - - 2013-09-14 09:52:07.033822 Z
    - Alexander Schier <allo@laxu.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.2.0
  status: :released
  release_time: 2013-09-27 13:13:06.731653 Z
  log_events: 
  - - 2013-09-14 09:50:45.135167 Z
    - Alexander Schier <allo@laxu.de>
    - created
    - ""
  - - 2013-09-27 13:13:06.731670 Z
    - Alexander Schier <allo@laxu.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.3.0
  status: :released
  release_time: 2013-11-26 18:48:08.578951 Z
  log_events: 
  - - 2013-09-24 22:31:27.086770 Z
    - Alexander Schier <allo@laxu.de>
    - created
    - ""
  - - 2013-11-26 18:48:08.578969 Z
    - Alexander Schier <allo@laxu.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.4.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2013-11-26 18:48:16.635268 Z
    - Alexander Schier <allo@laxu.de>
    - created
    - ""
