--- !ditz.rubyforge.org,2008-03-06/project 
name: django-bingo
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: django-bingo
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.0.0
  status: :released
  release_time: 2013-09-10 22:30:42 Z
  log_events: 
  - - 2013-09-12 23:05:01.756848 Z
    - Alexander Schier <allo@laxu.de>
    - created
    - ""
  - - 2013-09-12 23:05:33.478481 Z
    - Alexander Schier <allo@laxu.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.1.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2013-09-12 23:07:08.362653 Z
    - Alexander Schier <allo@laxu.de>
    - created
    - ""
